enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]
# 4 = 'secondary'
# 5 = 'secondary'
# 6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'

# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical   = 10
outer.left       = 10
# outer.top        = [{ monitor.'built-in' = 10 }, { monitor.main = 5 }, 5]
outer.top        = [{ monitor.'built-in' = 20 }, { monitor.main = 55 }, 55]
outer.bottom     = 10
# outer.bottom     = [{ monitor.'built-in' = 35 }, { monitor.main = 30}, 10]
outer.right      = 10

[mode.main.binding]
alt-enter = 'exec-and-forget /Applications/Ghostty.app/Contents/MacOS/ghostty'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-shift-c = 'split horizontal'
alt-shift-v = 'split vertical'

alt-f = 'fullscreen'

# cmd-s = 'layout v_accordion' # 'layout stacking' in i3
# cmd-w = 'layout h_accordion' # 'layout tabbed' in i3
# cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#cmd-space = 'focus toggle_tiling_floating'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'
cmd-0 = 'workspace 10'

cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
cmd-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

cmd-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'ea.browser.deta.surf'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-id = 'dev.vencord.vesktop'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.github.Electron'
run = 'move-node-to-workspace 7'
